{ "display_name":"Amazon EKS",
  "description": "SignalFx's integration with Elastic Container Service for Kubernetes (EKS).",
  "project_url": "https://github.com/signalfx/integrations/tree/master/aws-eks",
  "code": "https://aws.amazon.com/eks/",
  "featured": false,
  "logo_large": "integration_amazoneks%402x.png",
  "logo_small": "integration_amazoneks.png",
  "data_signature": "namespace:\"AWS/EKS\"",
  "in_app_categories": ["AWSservicesMonitored"],
  "browse_categories": ["Compute", "Containers"]
}
