code: https://github.com/signalfx/collectd/blob/master/src/java.c
data_signature: plugin:"GenericJMX"
description: The Java plugin for collectd embeds a Java virtual machine (JVM) into
  collectd and exposes the application programming interface (API) to Java programs.
display_name: Java
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-java/img/integrations_java%402x.png
logo_small: /images/repos/collectd-java/img/integrations_java.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-java
