browse_categories:
- Database
code: https://github.com/signalfx/collectd/blob/master/src/zookeeper.c
data_signature: plugin:"zookeeper"
description: Monitor ZooKeeper using the SignalFx collectd agent.
display_name: ZooKeeper
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-zookeeper/img/integrations_zookeeper%402x.png
logo_small: /images/repos/collectd-zookeeper/img/integrations_zookeeper.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-zookeeper
