browse_categories:
- Networking & Content Delivery
code: https://github.com/signalfx/collectd/blob/master/src/nginx.c
data_signature: plugin:"nginx"
description: Monitor NGINX using the SignalFx collectd plugin.
display_name: NGINX
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-nginx/img/integrations_nginx%402x.png
logo_small: /images/repos/collectd-nginx/img/integrations_nginx.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-nginx
