# *Required* The access token for the org that you wish to send metrics to.
signalFxAccessToken: ${SFX_ACCESS_TOKEN}

procFSPath: /hostfs/proc

logging:
  # Valid values are 'debug', 'info', 'warning', and 'error'
  level: info

# globalDimensions will be added to every datapoint that gets sent by the agent
globalDimensions:
  kubernetes_cluster: 'CLUSTER_NAME'
  kubernetes_role: master

monitors:
  - type: collectd/signalfx-metadata

  - type: collectd/docker
    dockerURL: unix:///var/run/docker.sock
    excludedImages:
      - ".*pause-amd64.*"
    dimensions:
      container_image: inspect:Config.Image
      container_id: inspect:Id
      container_spec_name: inspect:Config.Labels['io.kubernetes.container.name']
      # Duplicated for backwards compatibility
      container_name: inspect:Config.Labels['io.kubernetes.container.name']
      kubernetes_pod_name: inspect:Config.Labels['io.kubernetes.pod.name']
      kubernetes_pod_uid: inspect:Config.Labels['io.kubernetes.pod.uid']
      kubernetes_namespace: inspect:Config.Labels['io.kubernetes.pod.namespace']

collectd:
  readThreads: 5
  writeQueueLimitHigh: 500000
  writeQueueLimitLow: 400000
  timeout: 40
  logLevel: notice
