apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: signalfx-agent
    labels:
        version: 2.2.0
        app: signalfx-agent
spec:
    selector:
        matchLabels:
            app: signalfx-agent
    template:
        metadata:
            labels:
                app: signalfx-agent
                version: 2.2.0
        spec:
            hostNetwork: true
            restartPolicy: Always
            containers:
            - name: signalfx-agent
              image: quay.io/signalfx/signalfx-agent:2.2.0
              securityContext:
                privileged: true
              command:
              - /usr/bin/signalfx-agent
              - -config
              - /mnt/config/agent.yaml
              volumeMounts:
                - mountPath: /mnt/config
                  name: config
                - mountPath: /hostfs
                  name: hostfs
                  readOnly: true
                - mountPath: /var/run/docker.sock
                  name: docker
                  readOnly: true
              env:
              - name: SFX_ACCESS_TOKEN
                valueFrom:
                    secretKeyRef:
                        name: signalfx
                        key: access-token
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MY_NODE_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.nodeName
              - name: MY_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
            volumes:
              - name: config
                configMap:
                  name: signalfx-agent
              - hostPath:
                  path: /
                name: hostfs
              - hostPath:
                  path: /var/run/docker.sock
                name: docker
