browse_categories:
- Application Integration
code: https://github.com/signalfx/collectd/blob/master/src/write_kafka.c
data_signature: hostHasService:kafka
description: Monitor Kafka using the SignalFx collectd agent.
display_name: Kafka
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-kafka/img/integrations_kafka%402x.png
logo_small: /images/repos/collectd-kafka/img/integrations_kafka.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-kafka
