{ "display_name":"Kafka",
  "description": "Monitor Kafka using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-kafka",
  "code": "https://github.com/signalfx/collectd/blob/master/src/write_kafka.c",
  "featured": true,
  "logo_small": "/images/repos/collectd-kafka/img/integrations_kafka.png",
  "logo_large": "/images/repos/collectd-kafka/img/integrations_kafka%402x.png",
  "data_signature": "hostHasService:kafka",
  "in_app_categories": ["servicesMonitored"],
  "browse_categories": ["Application Integration"]
}
