browse_categories:
- Compute
- Containers
code: https://github.com/signalfx/docker-collectd-plugin
data_signature: plugin:"docker"
description: Monitor Docker using the SignalFx collectd agent.
display_name: Docker
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-docker/img/integrations_docker%402x.png
logo_small: /images/repos/collectd-docker/img/integrations_docker.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-docker
