browse_categories:
- Storage
- Analytics
code: https://github.com/signalfx/collectd-hadoop
data_signature: plugin:"apache_hadoop"
description: Monitor Hadoop using the SignalFx collectd agent.
display_name: Hadoop
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-hadoop/img/integrations_hadoop@2x.png
logo_small: /images/repos/collectd-hadoop/img/integrations_hadoop.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-hadoop
