{ "display_name":"VSphere",
  "description": "Monitor VSphere using the SignalFx-Vsphere application",
  "project_url": "https://github.com/signalfx/integrations/tree/master/vmware-vsphere",
  "code": "https://github.com/signalfx/signalfx-vsphere",
  "featured": false,
  "logo_large": "/images/repos/vsphere/img/integrations_vmwarevsphere.png",
  "logo_small": "/images/repos/vsphere/img/integrations_vmwarevsphere%402x.png",
  "data_signature": "metric_source:\"vsphere\"",
  "in_app_categories": ["servicesMonitored"]
}