browse_categories:
- Cloud infrastructure and services
code: https://github.com/signalfx/signalfx-vsphere
data_signature: metric_source:"vsphere"
description: Monitor vSphere using the SignalFx-vSphere application
display_name: vSphere
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/vmware-vsphere/img/integrations_vsphere%402x.png
logo_small: /images/repos/vmware-vsphere/img/integrations_vsphere.png
project_url: https://github.com/signalfx/integrations/tree/master/vmware-vsphere
