browse_categories:
- Database
code: https://github.com/signalfx/collectd-etcd
data_signature: plugin:"etcd"
description: Monitor etcd using the SignalFx collectd agent.
display_name: etcd
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-etcd/img/integrations_etcd%402x.png
logo_small: /images/repos/collectd-etcd/img/integrations_etcd.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-etcd
