{ "display_name":"AppDynamics",
  "description": "The SignalFx AppDynamics integration brings metrics captured through AppDynamics into SignalFx.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/appdynamics",
  "code": "https://github.com/signalfx/appd-integration",
  "featured": false,
  "logo_large": "/images/repos/appdynamics/img/integrations_appdynamics%402x.png",
  "logo_small": "/images/repos/appdynamics/img/integrations_appdynamics.png",
  "in_app_categories": ["servicesMonitored"],
  "browse_categories": ["Management Tools"]
}
