browse_categories:
- Management Tools
code: https://github.com/signalfx/collectd/blob/master/src/statsd.c
data_signature: plugin:"statsd"
description: The StatsD plugin for collectd aggregates and transmits metrics from
  StatsD.
display_name: StatsD
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-statsd/img/integrations_statsd%402x.png
logo_small: /images/repos/collectd-statsd/img/integrations_statsd.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-statsd
